# Generated by Django 4.2.1 on 2023-05-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={'verbose_name': 'Friendship request', 'verbose_name_plural': 'Friendship requests'},
        ),
    ]
